locale: zh-TW
timezone: Asia/Taipei

title: 我的部落格
name: SamYu
url: "https://samyu183201-arch.github.io"
baseurl: "/blog"
description: 分享技術、筆記與心得

minimal_mistakes_skin: "default"
remote_theme: "mmistakes/minimal-mistakes"

collections:
  posts:
    output: true

permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

nav: primary
