
locale: zh-TW
timezone: Asia/Taipei

title: "Sam.Blog"
name: "SamYu"
url: "https://samyu183201-arch.github.io"   
baseurl: "/blog"                           # 如果有子路徑就填，否則留空 ""

# 佈景主題
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # 可選：default, dark, dirt, neon, air, sunrise...

# 分頁設定
paginate: 10
paginate_path: /page:num/

# Plugins (GitHub Pages 允許的插件)
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-include-cache


# 預設值 (讓所有文章自動套用這些參數)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single      
      read_time: true
      comments: false
      share: false
      related: true


      
